server.port: 8003
server.error.include-message: always

# Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update

spring.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect

spring.datasource:
  url: jdbc:mysql://localhost:3306/review-db
  username: REVIEWSRV
  password: REVIEWSRV

spring.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    rp.rutepati: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/review-db
